// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/pet/pet.proto

package pet

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ascii         string                 `protobuf:"bytes,1,opt,name=ascii,proto3" json:"ascii,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_api_pet_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_api_pet_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_api_pet_pet_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetAscii() string {
	if x != nil {
		return x.Ascii
	}
	return ""
}

func (x *Pet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_pet_pet_proto protoreflect.FileDescriptor

const file_api_pet_pet_proto_rawDesc = "" +
	"\n" +
	"\x11api/pet/pet.proto\x12\x03pet\x1a\x17validate/validate.proto\"O\n" +
	"\x03Pet\x12\x1d\n" +
	"\x05ascii\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05ascii\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vdescriptionB\x1eZ\x1cgithub.com/webbsalad/pet;petb\x06proto3"

var (
	file_api_pet_pet_proto_rawDescOnce sync.Once
	file_api_pet_pet_proto_rawDescData []byte
)

func file_api_pet_pet_proto_rawDescGZIP() []byte {
	file_api_pet_pet_proto_rawDescOnce.Do(func() {
		file_api_pet_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pet_pet_proto_rawDesc), len(file_api_pet_pet_proto_rawDesc)))
	})
	return file_api_pet_pet_proto_rawDescData
}

var file_api_pet_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_pet_pet_proto_goTypes = []any{
	(*Pet)(nil), // 0: pet.Pet
}
var file_api_pet_pet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pet_pet_proto_init() }
func file_api_pet_pet_proto_init() {
	if File_api_pet_pet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pet_pet_proto_rawDesc), len(file_api_pet_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_pet_pet_proto_goTypes,
		DependencyIndexes: file_api_pet_pet_proto_depIdxs,
		MessageInfos:      file_api_pet_pet_proto_msgTypes,
	}.Build()
	File_api_pet_pet_proto = out.File
	file_api_pet_pet_proto_goTypes = nil
	file_api_pet_pet_proto_depIdxs = nil
}
