// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/pet/pet_service.proto

package pet

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetPetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetPetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetPetRequestMultiError, or
// nil if none found.
func (m *GetPetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetPetRequestMultiError(errors)
	}

	return nil
}

// GetPetRequestMultiError is an error wrapping multiple validation errors
// returned by GetPetRequest.ValidateAll() if the designated constraints
// aren't met.
type GetPetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPetRequestMultiError) AllErrors() []error { return m }

// GetPetRequestValidationError is the validation error returned by
// GetPetRequest.Validate if the designated constraints aren't met.
type GetPetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPetRequestValidationError) ErrorName() string { return "GetPetRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetPetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPetRequestValidationError{}

// Validate checks the field values on PutPetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PutPetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutPetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PutPetRequestMultiError, or
// nil if none found.
func (m *PutPetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PutPetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAscii()) < 1 {
		err := PutPetRequestValidationError{
			field:  "Ascii",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) < 1 {
		err := PutPetRequestValidationError{
			field:  "Description",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PutPetRequestMultiError(errors)
	}

	return nil
}

// PutPetRequestMultiError is an error wrapping multiple validation errors
// returned by PutPetRequest.ValidateAll() if the designated constraints
// aren't met.
type PutPetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutPetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutPetRequestMultiError) AllErrors() []error { return m }

// PutPetRequestValidationError is the validation error returned by
// PutPetRequest.Validate if the designated constraints aren't met.
type PutPetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutPetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutPetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutPetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutPetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutPetRequestValidationError) ErrorName() string { return "PutPetRequestValidationError" }

// Error satisfies the builtin error interface
func (e PutPetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutPetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutPetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutPetRequestValidationError{}

// Validate checks the field values on PutPetResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PutPetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PutPetResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PutPetResponseMultiError,
// or nil if none found.
func (m *PutPetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PutPetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PutPetResponseMultiError(errors)
	}

	return nil
}

// PutPetResponseMultiError is an error wrapping multiple validation errors
// returned by PutPetResponse.ValidateAll() if the designated constraints
// aren't met.
type PutPetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PutPetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PutPetResponseMultiError) AllErrors() []error { return m }

// PutPetResponseValidationError is the validation error returned by
// PutPetResponse.Validate if the designated constraints aren't met.
type PutPetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutPetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutPetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutPetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutPetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutPetResponseValidationError) ErrorName() string { return "PutPetResponseValidationError" }

// Error satisfies the builtin error interface
func (e PutPetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutPetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutPetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutPetResponseValidationError{}
