// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/pet/pet_service.proto

package pet

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	mi := &file_api_pet_pet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pet_pet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_api_pet_pet_service_proto_rawDescGZIP(), []int{0}
}

type PutPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ascii         string                 `protobuf:"bytes,1,opt,name=ascii,proto3" json:"ascii,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPetRequest) Reset() {
	*x = PutPetRequest{}
	mi := &file_api_pet_pet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPetRequest) ProtoMessage() {}

func (x *PutPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pet_pet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPetRequest.ProtoReflect.Descriptor instead.
func (*PutPetRequest) Descriptor() ([]byte, []int) {
	return file_api_pet_pet_service_proto_rawDescGZIP(), []int{1}
}

func (x *PutPetRequest) GetAscii() string {
	if x != nil {
		return x.Ascii
	}
	return ""
}

func (x *PutPetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PutPetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPetResponse) Reset() {
	*x = PutPetResponse{}
	mi := &file_api_pet_pet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPetResponse) ProtoMessage() {}

func (x *PutPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pet_pet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPetResponse.ProtoReflect.Descriptor instead.
func (*PutPetResponse) Descriptor() ([]byte, []int) {
	return file_api_pet_pet_service_proto_rawDescGZIP(), []int{2}
}

var File_api_pet_pet_service_proto protoreflect.FileDescriptor

const file_api_pet_pet_service_proto_rawDesc = "" +
	"\n" +
	"\x19api/pet/pet_service.proto\x12\x03pet\x1a\x11api/pet/pet.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x0f\n" +
	"\rGetPetRequest\"Y\n" +
	"\rPutPetRequest\x12\x1d\n" +
	"\x05ascii\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05ascii\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vdescription\"\x10\n" +
	"\x0ePutPetResponse2\x86\x01\n" +
	"\n" +
	"PetService\x124\n" +
	"\x06GetPet\x12\x12.pet.GetPetRequest\x1a\b.pet.Pet\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/pet\x12B\n" +
	"\x06PutPet\x12\x12.pet.PutPetRequest\x1a\x13.pet.PutPetResponse\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\x1a\x04/petB\x1eZ\x1cgithub.com/webbsalad/pet;petb\x06proto3"

var (
	file_api_pet_pet_service_proto_rawDescOnce sync.Once
	file_api_pet_pet_service_proto_rawDescData []byte
)

func file_api_pet_pet_service_proto_rawDescGZIP() []byte {
	file_api_pet_pet_service_proto_rawDescOnce.Do(func() {
		file_api_pet_pet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pet_pet_service_proto_rawDesc), len(file_api_pet_pet_service_proto_rawDesc)))
	})
	return file_api_pet_pet_service_proto_rawDescData
}

var file_api_pet_pet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_pet_pet_service_proto_goTypes = []any{
	(*GetPetRequest)(nil),  // 0: pet.GetPetRequest
	(*PutPetRequest)(nil),  // 1: pet.PutPetRequest
	(*PutPetResponse)(nil), // 2: pet.PutPetResponse
	(*Pet)(nil),            // 3: pet.Pet
}
var file_api_pet_pet_service_proto_depIdxs = []int32{
	0, // 0: pet.PetService.GetPet:input_type -> pet.GetPetRequest
	1, // 1: pet.PetService.PutPet:input_type -> pet.PutPetRequest
	3, // 2: pet.PetService.GetPet:output_type -> pet.Pet
	2, // 3: pet.PetService.PutPet:output_type -> pet.PutPetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pet_pet_service_proto_init() }
func file_api_pet_pet_service_proto_init() {
	if File_api_pet_pet_service_proto != nil {
		return
	}
	file_api_pet_pet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pet_pet_service_proto_rawDesc), len(file_api_pet_pet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pet_pet_service_proto_goTypes,
		DependencyIndexes: file_api_pet_pet_service_proto_depIdxs,
		MessageInfos:      file_api_pet_pet_service_proto_msgTypes,
	}.Build()
	File_api_pet_pet_service_proto = out.File
	file_api_pet_pet_service_proto_goTypes = nil
	file_api_pet_pet_service_proto_depIdxs = nil
}
