syntax = "proto3";

package pet;

option go_package = "github.com/webbsalad/pet;pet";

import "api/pet/pet.proto";
import "google/api/annotations.proto";
import "validate/validate.proto";

service PetService {
    rpc GetPet(GetPetRequest) returns (Pet) {
        option (google.api.http) = {
            get: "/pet",
        };
    };

    rpc PutPet(PutPetRequest) returns (PutPetResponse) {
        option (google.api.http) = {
        put: "/pet",
            body: "*"
        };
    };

}


message GetPetRequest {
}

message PutPetRequest {
    string ascii = 1 [(validate.rules).string = {min_len: 1}];
    string description = 2 [(validate.rules).string = {min_len: 1}];
}

message PutPetResponse {
}